[proton-pass]
source = "git"
git = "https://github.com/ProtonMail/WebClients.git"
use_max_tag = true
include_regex = "proton-pass@.*"
exclude_regex = '.*(alpha|rc|\d{3}).*'
from_pattern = 'proton-pass@(.+)'
to_pattern = '\1'
